import type { MissionDefinition } from "../mission-types";

export const COMPARISON_MISSION: MissionDefinition = {
  id: "comparison",
  label: "Scene C",
  title: "Compare three policies",
  objective: "Give three fee policies the same trades, reveal them one at a time, and see why no winner is declared.",
  duration: "3–4 min",
  dataMode: "REPLAY",
  firstStageId: "choose-case",
  stages: [
    { id: "choose-case", index: 1, label: "Choose case", whatHappened: "Four preregistered cases are available.", objective: "Choose the shared market/evidence input.", known: "Each case has a frozen checksum and replay window.", unknown: "How each policy behaves on this case.", whyItMatters: "The case must be selected before inspecting outcomes.", outputs: [{ id: "comparison-case", kind: "COMPARISON", title: "False-rumor control selected", summary: "Zero observed swaps; this case has no economic row by design.", dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-case" }], choices: [{ id: "select-false-rumor", label: "Use false-rumor control", description: "Start with the clearest safety negative control.", outcome: "ACCEPTED", reveal: ["comparison-case"], nextStageId: "lock-input" }] },
    { id: "lock-input", index: 2, label: "Lock input", whatHappened: "The case is selected, but the shared input has not been verified.", objective: "Inspect and lock the input checksum.", known: "All three policies must receive identical swaps and timestamps.", unknown: "No policy result has been revealed.", whyItMatters: "Matched inputs prevent the preferred policy from receiving easier data.", outputs: [{ id: "comparison-input", kind: "COMPARISON", title: "Matched input locked", summary: "Checksum a69691…03fc22 is shared by all three policies.", detail: ["Observed swaps: 0", "Economic row: absent", "Expected evidence state: WATCH"], dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-input" }], choices: [{ id: "lock-checksum", label: "Lock matched input", description: "Bind every policy to the same preregistered case.", outcome: "ACCEPTED", reveal: ["comparison-input"], nextStageId: "predict" }] },
    { id: "predict", index: 3, label: "Predict", whatHappened: "The common input is locked.", objective: "Make a non-binding prediction before results appear.", known: "Static has no signal; volatility-only has market data; Tinjau also has evidence.", unknown: "Validated benchmark outputs.", whyItMatters: "The prediction exposes intuition but cannot alter the benchmark.", outputs: [{ id: "comparison-prediction", kind: "COMPARISON", title: "Prediction recorded", summary: "Your prediction is commentary only and does not change inputs or results.", dataMode: "SIMULATED", capabilityId: "policy-benchmark" }], choices: [
      { id: "predict-static", label: "Predict static", description: "Expect no dynamic response to be safest.", outcome: "ACCEPTED", reveal: ["comparison-prediction"], nextStageId: "run-static" },
      { id: "predict-volatility", label: "Predict volatility-only", description: "Expect market telemetry alone to be safest.", outcome: "ACCEPTED", reveal: ["comparison-prediction"], nextStageId: "run-static" },
      { id: "predict-tinjau", label: "Predict Tinjau", description: "Expect evidence-aware containment to be safest.", outcome: "ACCEPTED", reveal: ["comparison-prediction"], nextStageId: "run-static" },
    ] },
    { id: "run-static", index: 4, label: "Static", whatHappened: "The prediction is recorded and the benchmark input remains unchanged.", objective: "Reveal the static-fee policy behavior.", known: "Static fee remains at 500 pips.", unknown: "Comparable validated economic metrics.", whyItMatters: "Static is the control policy, not a deliberately weak strawman.", outputs: [{ id: "comparison-static", kind: "COMPARISON", title: "Static fee revealed", summary: "Constant 500 pips; no market or evidence access.", detail: ["Economic values: no row for this case"], dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-static" }], choices: [{ id: "run-static-policy", label: "Run static policy", description: "Reveal only the preregistered static behavior.", outcome: "ACCEPTED", reveal: ["comparison-static"], nextStageId: "run-volatility" }] },
    { id: "run-volatility", index: 5, label: "Volatility-only", whatHappened: "Static behavior is visible.", objective: "Reveal the volatility-only policy under the same input.", known: "It may use market telemetry but no filing or rumor semantics.", unknown: "T5 economic outputs remain pending.", whyItMatters: "This is the strongest non-event-aware dynamic comparator.", outputs: [{ id: "comparison-volatility", kind: "COMPARISON", title: "Volatility-only revealed", summary: "Same ceiling and decay envelope; no evidence access.", detail: ["Variants: k=2, k=3, k=5", "Fired on the neutral control at every variant"], dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-volatility" }], choices: [{ id: "run-volatility-policy", label: "Run volatility-only", description: "Reveal its preregistered behavior without inventing metrics.", outcome: "ACCEPTED", reveal: ["comparison-volatility"], nextStageId: "run-tinjau" }] },
    { id: "run-tinjau", index: 6, label: "Tinjau", whatHappened: "Both comparison policies are visible under the matched input.", objective: "Reveal Tinjau's event-aware behavior.", known: "Evidence access cannot bypass market confirmation.", unknown: "The benchmark has not produced validated outcomes.", whyItMatters: "The benchmark has since run. Its economic answer reverses between two metric bases, so the surviving difference is behavioural.", outputs: [{ id: "comparison-tinjau", kind: "COMPARISON", title: "Tinjau revealed", summary: "Matched telemetry plus the evidence path; rumor remains capped at WATCH.", detail: ["Fee action: none for false rumor", "Declined at every trigger setting tested"], dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-tinjau" }], choices: [{ id: "run-tinjau-policy", label: "Run Tinjau policy", description: "Reveal event-aware containment under the matched input.", outcome: "ACCEPTED", reveal: ["comparison-tinjau"], nextStageId: "compare" }] },
    { id: "compare", index: 7, label: "Compare", whatHappened: "All three policy definitions are now visible.", objective: "Inspect the claim gate without forcing a winner.", known: "This case has no observed swaps, so it carries no economic row by design.", unknown: "Which policy earned more. The benchmark ran and could not answer it.", whyItMatters: "A missing row stays missing. It is never read as zero, and never as a favourable result.", outputs: [{ id: "comparison-result", kind: "COMPARISON", title: "Claim gate remains closed", summary: "The benchmark ran. All 27 comparable cells reverse between the two metric bases, so no winner is declared.", detail: ["This case has no economic row: zero observed swaps", "Across the cases that do: 27 of 27 reverse", "canClaimLossAvoided: false"], dataMode: "REPLAY", capabilityId: "policy-benchmark", renderKey: "comparison-result" }], choices: [{ id: "inspect-claim-gate", label: "Inspect claim gate", description: "Finish with the evidence-supported conclusion only.", outcome: "ACCEPTED", reveal: ["comparison-result"], completeMission: true } ] },
  ],
};
