import type { MissionDefinition } from "../mission-types";

const blockedProtect = {
  id: "protect-blocked",
  title: "PROTECT blocked",
  previousState: "WATCH" as const,
  nextState: "WATCH" as const,
  cause: "Official evidence alone does not satisfy the final action gate.",
  evidence: "A qualifying SEC filing exists. Market confirmation has not been obtained, and no protection may start without it.",
  guardrail: "Fresh OKX/X Layer confirmation is required before PROTECT.",
  allowed: "Inspect provenance, market inputs, and the current risk record.",
  prohibited: "Apply the final fee action or claim an end-to-end transaction.",
  dataMode: "REPLAY" as const,
  capabilityId: "confirmation-engine",
};

export const CONFIRMED_MISSION: MissionDefinition = {
  id: "confirmed",
  label: "Scene B",
  title: "Verify an official event",
  objective: "Follow a real SEC filing to the point where the market check refuses to confirm it.",
  duration: "5–6 min",
  dataMode: "REPLAY",
  firstStageId: "listen",
  stages: [
    { id: "listen", index: 1, label: "Listen", whatHappened: "A new SEC filing has entered the official intake queue.", objective: "Open the filing as potential evidence.", known: "The issuer and accession are available.", unknown: "Material terms, asset mapping, and policy consequence.", whyItMatters: "Official origin is stronger evidence, but it is not automatic action authority.", outputs: [{ id: "official-signal", kind: "SIGNAL", title: "Official filing observed", summary: "NVIDIA Form 8-K accession captured from SEC EDGAR.", dataMode: "REPLAY", capabilityId: "official-intake", renderKey: "official-signal" }], choices: [{ id: "inspect-filing", label: "Inspect filing", description: "Open the source-pinned official signal.", outcome: "ACCEPTED", reveal: ["official-signal"], nextStageId: "retrieve" }] },
    { id: "retrieve", index: 2, label: "Retrieve", whatHappened: "The official accession is known.", objective: "Retrieve the filing and preserve source provenance.", known: "SEC EDGAR is the canonical origin.", unknown: "The relevant obligation and its bounded amount.", whyItMatters: "A canonical filing can be independently inspected outside Tinjau.", outputs: [{ id: "official-source", kind: "SOURCE", title: "SEC source preserved", summary: "The filing and Exhibit 99.1 are source-linked under one official accession.", detail: ["Published: 2026-08-17 12:41:33Z", "Source class: OFFICIAL"], dataMode: "REPLAY", capabilityId: "official-intake", renderKey: "source-intake", sourceUrl: "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000069/nvda-20260817.htm" }], choices: [{ id: "retrieve-filing", label: "Retrieve official source", description: "Preserve source URL, author, timestamp, and accession.", outcome: "ACCEPTED", reveal: ["official-source"], nextStageId: "understand" }] },
    { id: "understand", index: 3, label: "Understand", whatHappened: "The official filing is available for structured analysis.", objective: "Extract the obligation, company, token, and event type.", known: "The issuer disclosed residual value guaranties.", unknown: "Independent support and current market consequence.", whyItMatters: "AI extracts meaning while bonded fields remain source-verifiable.", outputs: [{ id: "official-normalized", kind: "CLAIM", title: "Official claim normalized", summary: "Residual value guaranties capped at $105bn map to wNVDAx.", detail: ["Event: material agreement + direct obligation", "Confidence: MEDIUM"], dataMode: "REPLAY", capabilityId: "evidence-graph", renderKey: "processing-understand" }], choices: [{ id: "normalize-filing", label: "Normalize filing", description: "Extract the bonded event fields.", outcome: "ACCEPTED", reveal: ["official-normalized"], nextStageId: "relate" }] },
    { id: "relate", index: 4, label: "Relate", whatHappened: "Official and news claims describe related versions of the event.", objective: "Resolve support, self-revision, and syndication.", known: "The filing is official; several articles repeat two report origins.", unknown: "Whether market evidence is fresh enough to complete promotion.", whyItMatters: "Official status strengthens evidence but does not erase conflicting magnitudes.", outputs: [{ id: "official-graph", kind: "EVIDENCE", title: "Evidence graph resolved", summary: "Official filing anchors the event; syndicated claims remain grouped by origin.", detail: ["Official origin: 1", "Supporting news origins: 2", "Duplicates: 2"], dataMode: "REPLAY", capabilityId: "evidence-graph", renderKey: "evidence-circuit" }], choices: [{ id: "resolve-evidence", label: "Resolve evidence graph", description: "Keep official support and duplicate groups explicit.", outcome: "ACCEPTED", reveal: ["official-graph"], nextStageId: "decide" }] },
    { id: "decide", index: 5, label: "Decide", whatHappened: "A qualifying official event has passed the evidence gate.", objective: "Set the maximum state allowed before market confirmation.", known: "The official filing is real and present. The bonded-evidence condition is computed for this scenario rather than assumed: on 2026-08-21 three independent model parses of this exact filing all returned a result, and both key fields (the event type and the affected token) agreed.", unknown: "Fresh basis, drawdown, flow, and exit-depth confirmation.", whyItMatters: "Evidence creates a candidate, not permission to bypass the independent market gate.", outputs: [{ id: "official-watch", kind: "RISK", title: "Conditional WATCH", summary: "Official evidence passed, with the bonded-evidence leg computed from a live parse of the filing rather than assumed. PROTECT remains conditional on market confirmation.", detail: ["OFFICIAL_FILING", "BONDED_EVIDENCE_PASSED", "Bonded bit: computed on 2026-08-21, not assumed", "Computed and assumed both resolve WATCH, so this run changed no verdict"], dataMode: "REPLAY", capabilityId: "risk-policy", renderKey: "risk-state" }], choices: [
      { id: "protect-before-market", label: "Enter PROTECT now", description: "Treat official status as sufficient for fee action.", outcome: "REJECTED", reasonCode: "MARKET_DATA_UNAVAILABLE", reveal: [], modal: blockedProtect },
      { id: "hold-for-market", label: "Hold for market gate", description: "Record the evidence-qualified WATCH candidate.", outcome: "ACCEPTED", reveal: ["official-watch"], nextStageId: "confirm", modal: { ...blockedProtect, id: "official-watch-entered", title: "WATCH retained", cause: "The evidence gate passed, but the market gate has not." } },
    ] },
    { id: "confirm", index: 6, label: "Confirm", whatHappened: "The evidence-qualified state is waiting on market corroboration.", objective: "Run the OKX reference and X Layer telemetry checks.", known: "The X Layer leg returns a fresh reading. The OKX reference leg is closed and returns nothing.", unknown: "Whether the price fall lasted long enough to count as a real dislocation.", whyItMatters: "The gate ran and refused. A refusal that names the rule it failed is a result, not a missing measurement.", outputs: [{ id: "official-market", kind: "MARKET", title: "Market gate refused to confirm", summary: "The X Layer leg measured the price fall and then watched it come back. Only 9.7% of the fall was still there at the median observation across the 300 seconds after the trough, against the 50% the rule requires, so it was a wick.", detail: ["Status: NOT_CONFIRMED", "Fresh: true", "Drawdown measured: 234.86 bps", "Anti-wick check: failed at 9.7% retained, 50% required", "OKX reference leg: unavailable, reference market closed", "Current state: WATCH"], dataMode: "OBSERVED", capabilityId: "confirmation-engine", renderKey: "market-confirmation" }], choices: [{ id: "run-market-gate", label: "Run market gate", description: "Inspect available adapter evidence without manufacturing a conclusion.", outcome: "ACCEPTED", reveal: ["official-market"], nextStageId: "record", modal: { ...blockedProtect, id: "official-market-not-confirmed", title: "Market did not confirm", cause: "The market leg ran and returned NOT_CONFIRMED.", evidence: "The fall did not persist: 9.7% of it remained at the median observation over the 300 seconds after the trough, below the 50% the anti-wick rule requires." } }] },
    { id: "record", index: 7, label: "Record", whatHappened: "The market gate refused to confirm, so the current state remains WATCH.", objective: "Prepare the current versioned risk record without a transaction claim.", known: "Evidence commitment, reasons, expiry, and WATCH state are available.", unknown: "Whether this particular scenario ever reaches an action.", whyItMatters: "The path exists end to end. This scenario simply does not reach the end of it, and that is the result rather than a gap.", outputs: [{ id: "official-record", kind: "RECORD", title: "Current WATCH record prepared", summary: "This record was posted to the registry on X Layer Testnet on 2026-08-21. It authorises no action, so there is no fee transaction attached to it.", detail: ["Action authorized: false", "Posted: block 38,875,116 on X Layer Testnet", "Transaction: 0x7edfb15d…0ad5ff44da16253dfabe1191843ebbacf584c2daabc2ad07c4fdd507", "No fee transaction: none was authorised"], dataMode: "REPLAY", capabilityId: "risk-registry", renderKey: "risk-record" }], choices: [{ id: "prepare-current-record", label: "Prepare current record", description: "Bind the evidence-qualified WATCH result.", outcome: "ACCEPTED", reveal: ["official-record"], nextStageId: "act" }] },
    { id: "act", index: 8, label: "Act", whatHappened: "The current implementation has reached its truthful stopping point.", objective: "Choose whether to stop at current truth or inspect the intended lifecycle as replay.", known: "No final fee transaction can be applied from this record.", unknown: "Observed end-to-end PROTECT execution under the final contracts.", whyItMatters: "Replay can teach the lifecycle only when it cannot be mistaken for current execution.", outputs: [
      { id: "current-action-none", kind: "ACTION", title: "Current action unavailable", summary: "WATCH has no fee authorization and no final transaction.", detail: ["Current action: NONE", "Fee hook: deployed on X Layer Testnet, reading this registry", "Reason: WATCH authorises no fee change"], dataMode: "REPLAY", capabilityId: "fee-hook", renderKey: "action" },
      { id: "replay-protect", kind: "ACTION", title: "Lifecycle replay: PROTECT", summary: "A preregistered target path applies a bounded fee inside the historical envelope. The same envelope was enforced for real on 2026-08-21, in a paired-pool run on two builder-controlled testnet pools.", detail: ["Mode: REPLAY", "Maximum fee: 20,000 pips", "Maximum duration: 21,600s", "Paired-pool run: the gap came to 100.195% of what the fee difference alone must produce, so it is a conformance test of the mechanism and not a discovery", "Its PROTECT was constructed by hand, so it establishes nothing about whether Tinjau acts at the right time"], dataMode: "REPLAY", capabilityId: "fee-hook", renderKey: "replay-protect" },
    ], choices: [
      { id: "apply-current-fee", label: "Apply final fee now", description: "Request a transaction from the incomplete final path.", outcome: "UNAVAILABLE", reasonCode: "MARKET_DATA_UNAVAILABLE", reveal: ["current-action-none"], modal: blockedProtect },
      { id: "continue-with-replay", label: "Continue with lifecycle replay", description: "Switch explicitly to the pre-registered target lifecycle.", outcome: "ACCEPTED", reveal: ["current-action-none", "replay-protect"], nextStageId: "recover", enableReplay: true, modal: { id: "replay-protect-entered", title: "REPLAY entered PROTECT", previousState: "WATCH", nextState: "PROTECT", cause: "You explicitly started a lifecycle replay; this is not current execution.", evidence: "Pre-registered policy envelope and historical bounded-hook behavior.", guardrail: "REPLAY remains visible and carries no current transaction claim.", allowed: "Inspect bounded fee, expiry, and decay behavior.", prohibited: "Present the replay as live or applied by final contracts.", dataMode: "REPLAY", capabilityId: "fee-hook" } },
    ] },
    { id: "recover", index: 9, label: "Recover", whatHappened: "The replayed protection window has reached expiry.", objective: "Apply deterministic decay and return the replay to baseline.", known: "The fee ceiling, duration, and decay schedule are bounded.", unknown: "No current transaction exists because this branch is replay.", whyItMatters: "Bounded protection must remove its own authority over time.", outputs: [{ id: "replay-recovery", kind: "RECOVERY", title: "Lifecycle replay returned to NORMAL", summary: "PROTECT expired, decayed through the bounded curve, and reached baseline.", detail: ["PROTECT → EXPIRED → DECAYED", "Final state: NORMAL", "Current tx: none"], dataMode: "REPLAY", capabilityId: "fee-hook", renderKey: "recovery" }], choices: [{ id: "run-replay-decay", label: "Run replayed decay", description: "Advance the target lifecycle to its deterministic baseline.", outcome: "ACCEPTED", reveal: ["replay-recovery"], completeMission: true, modal: { id: "replay-normal", title: "REPLAY returned to NORMAL", previousState: "PROTECT", nextState: "NORMAL", cause: "The replayed protection lifetime and decay completed.", evidence: "Historical bounded-fee envelope and deterministic target lifecycle.", guardrail: "Recovery is time-bound and cannot be held open by the model.", allowed: "Return to the baseline fee in replay.", prohibited: "Claim a live transaction or current final deployment.", dataMode: "REPLAY", capabilityId: "fee-hook" } }] },
  ],
};
