import type { MissionDefinition } from "../mission-types";

const blockedFeeModal = {
  id: "rumor-fee-blocked",
  title: "Aggressive fee blocked",
  cause: "The only new signal is an unverified social claim.",
  evidence: "No official source and no independent corroboration are available.",
  guardrail: "Rumor-only evidence cannot authorize PROTECT or a fee increase.",
  allowed: "Retrieve the source and continue evidence checks.",
  prohibited: "Raise the fee or publish the claim as fact.",
  dataMode: "SIMULATED" as const,
  capabilityId: "risk-policy",
};

export const RUMOR_MISSION: MissionDefinition = {
  id: "rumor",
  label: "Scene A",
  title: "Contain a rumor",
  objective: "Watch four outlets carrying one story collapse into one source, and the fee stay where it is.",
  duration: "4–5 min",
  dataMode: "REPLAY",
  firstStageId: "listen",
  stages: [
    {
      id: "listen", index: 1, label: "Listen",
      whatHappened: "A new claim has appeared in the monitored signal queue.",
      objective: "Inspect the signal before assigning credibility.",
      known: "One potential signal exists. Its content has not been retrieved.",
      unknown: "Author, original source, independence, and official support.",
      whyItMatters: "Discovery is not confirmation. The system starts with no action authority.",
      outputs: [{ id: "rumor-signal", kind: "SIGNAL", title: "Potential X signal", summary: "A simulated post claims NVIDIA accepted a $250bn financing backstop.", dataMode: "SIMULATED", capabilityId: "x-listener", renderKey: "rumor-signal", sourceUrl: null }],
      choices: [{ id: "inspect-signal", label: "Inspect signal", description: "Open the captured claim without promoting it.", outcome: "ACCEPTED", reveal: ["rumor-signal"], nextStageId: "retrieve" }],
    },
    {
      id: "retrieve", index: 2, label: "Retrieve",
      whatHappened: "The captured claim is visible, but its provenance is unresolved.",
      objective: "Preserve the source identity and retrieve the reporting chain.",
      known: "The social input is simulated and has no resolvable public URL.",
      unknown: "Whether any source supports the amount or obligation.",
      whyItMatters: "Tinjau must preserve a missing source instead of inventing one.",
      outputs: [{ id: "rumor-source-chain", kind: "SOURCE", title: "Source chain retrieved", summary: "One Wall Street Journal origin and several syndicated reports are identified.", detail: ["Original social URL: unavailable", "News chain: replayed and source-linked"], dataMode: "REPLAY", capabilityId: "official-intake", renderKey: "source-intake", sourceUrl: "https://www.cnbc.com/2026/07/27/nvidia-and-openai-in-talks-for-up-to-250-billion-dollar-ai-backstop.html" }],
      choices: [
        { id: "raise-fee-early", label: "Raise fee now", description: "Treat the social claim as sufficient authority.", outcome: "REJECTED", reasonCode: "RUMOR_ONLY", reveal: [], modal: blockedFeeModal },
        { id: "retrieve-origin", label: "Retrieve source chain", description: "Trace the claim to its original reporting.", outcome: "ACCEPTED", reveal: ["rumor-source-chain"], nextStageId: "understand" },
      ],
    },
    {
      id: "understand", index: 3, label: "Understand",
      whatHappened: "The source chain has been preserved with timestamps and provenance limits.",
      objective: "Normalize the claim, company, token, and event type.",
      known: "The reporting concerns a contingent financial obligation involving NVIDIA.",
      unknown: "Whether the $250bn figure is official or independently verified.",
      whyItMatters: "AI structures ambiguous language; it does not authorize the pool action.",
      outputs: [{ id: "rumor-normalized", kind: "CLAIM", title: "Claim normalized", summary: "NVIDIA CORPORATION → wNVDAx → contingent financial obligation.", detail: ["Assertion: talks around financing guarantees", "Confidence: LOW"], dataMode: "REPLAY", capabilityId: "evidence-graph", renderKey: "processing-understand" }],
      choices: [{ id: "normalize-claim", label: "Normalize claim", description: "Extract structured meaning while retaining uncertainty.", outcome: "ACCEPTED", reveal: ["rumor-normalized"], nextStageId: "relate" }],
    },
    {
      id: "relate", index: 4, label: "Relate",
      whatHappened: "Five reports now appear related to the same alleged event.",
      objective: "Determine which reports are genuinely independent.",
      known: "Several publishers repeat one origin report.",
      unknown: "Whether any independent or official support exists.",
      whyItMatters: "Counting syndication as corroboration would turn popularity into false authority.",
      outputs: [{ id: "rumor-graph", kind: "EVIDENCE", title: "Evidence graph resolved", summary: "Four reporting outlets collapse to one origin; the social claim adds no authority.", detail: ["Origin groups: 1 usable", "Duplicates: 3", "Official support: none"], dataMode: "REPLAY", capabilityId: "evidence-graph", renderKey: "evidence-circuit" }],
      choices: [
        { id: "count-reposts", label: "Count every report", description: "Treat repeated coverage as independent support.", outcome: "REJECTED", reasonCode: "DUPLICATE_SYNDICATION", reveal: [], modal: { ...blockedFeeModal, id: "duplicates-rejected", title: "Syndication collapsed", cause: "Multiple outlets repeat the same origin report.", evidence: "The independence group is identical across the syndicated claims.", guardrail: "Duplicate reports count once, not as independent corroboration." } },
        { id: "collapse-duplicates", label: "Collapse duplicates", description: "Group reports by their actual origin.", outcome: "ACCEPTED", reveal: ["rumor-graph"], nextStageId: "decide" },
      ],
    },
    {
      id: "decide", index: 5, label: "Decide",
      whatHappened: "The evidence graph has one usable non-official origin and no official support.",
      objective: "Choose a risk response that respects the evidence ceiling.",
      known: "The promotion ceiling is WATCH.",
      unknown: "Market consequence and whether an official filing will emerge.",
      whyItMatters: "The deterministic policy sets the maximum state, not the model.",
      outputs: [{ id: "rumor-watch", kind: "RISK", title: "WATCH recorded", summary: "Rumor observed. Official support absent. Aggressive fee blocked.", detail: ["SINGLE_SOURCE", "DUPLICATE_SYNDICATION", "NO_OFFICIAL_CONFIRMATION"], dataMode: "REPLAY", capabilityId: "risk-policy", renderKey: "risk-state" }],
      choices: [
        { id: "force-protect", label: "Force PROTECT", description: "Override the evidence ceiling and widen the fee.", outcome: "REJECTED", reasonCode: "NO_OFFICIAL_CONFIRMATION", reveal: [], modal: blockedFeeModal },
        { id: "set-watch", label: "Hold at WATCH", description: "Record caution without authorizing a fee action.", outcome: "ACCEPTED", reveal: ["rumor-watch"], nextStageId: "confirm", modal: { id: "watch-entered", title: "WATCH entered", previousState: "NORMAL", nextState: "WATCH", cause: "A material rumor exists without enough promotion authority.", evidence: "One usable news origin; no official confirmation.", guardrail: "WATCH can raise attention, never the aggressive fee.", allowed: "Continue market checks and preserve the record.", prohibited: "Apply PROTECT or publish the rumor as fact.", dataMode: "REPLAY", capabilityId: "risk-policy" } },
      ],
    },
    {
      id: "confirm", index: 6, label: "Confirm",
      whatHappened: "WATCH is active, but no market conclusion has been drawn.",
      objective: "Check whether fresh OKX and X Layer data can confirm a discontinuity.",
      known: "The replay window contains zero observed swaps.",
      unknown: "Basis, drawdown, velocity, and executable exit depth.",
      whyItMatters: "Unavailable data means Tinjau could not look; it is not a negative confirmation.",
      outputs: [{ id: "rumor-market-unavailable", kind: "MARKET", title: "Market confirmation unavailable", summary: "No economic row exists for this zero-swap replay window.", detail: ["Status: UNAVAILABLE", "Fresh: false", "Action authority: unchanged"], dataMode: "OBSERVED", capabilityId: "confirmation-engine", renderKey: "market-confirmation" }],
      choices: [{ id: "check-market", label: "Check market gate", description: "Request the available OKX/X Layer confirmation inputs.", outcome: "ACCEPTED", reveal: ["rumor-market-unavailable"], nextStageId: "record", modal: { id: "market-unavailable", title: "Market data unavailable", previousState: "WATCH", nextState: "WATCH", cause: "The replay window contains no observed swaps.", evidence: "No basis, velocity, or exit-depth measurement can be produced.", guardrail: "Missing market data cannot promote a new PROTECT.", allowed: "Retain WATCH until expiry or new evidence.", prohibited: "Impute market confirmation or create an economic result.", dataMode: "OBSERVED", capabilityId: "confirmation-engine" } }],
    },
    {
      id: "record", index: 7, label: "Record",
      whatHappened: "Evidence and market checks have reached a fail-closed result.",
      objective: "Create the versioned off-chain risk record.",
      known: "State, reasons, evidence commitment, and expiry are available.",
      unknown: "No final on-chain transaction exists.",
      whyItMatters: "A reusable record makes the decision inspectable without trusting this screen.",
      outputs: [{ id: "rumor-record", kind: "RECORD", title: "Risk record prepared", summary: "Versioned WATCH record with evidence commitment and 24-hour expiry.", detail: ["Action authorized: false", "Transaction: none"], dataMode: "REPLAY", capabilityId: "risk-registry", renderKey: "risk-record" }],
      choices: [{ id: "record-watch", label: "Prepare risk record", description: "Bind state, reasons, evidence, and expiry.", outcome: "ACCEPTED", reveal: ["rumor-record"], nextStageId: "act" }],
    },
    {
      id: "act", index: 8, label: "Act",
      whatHappened: "The WATCH record exists with no fee authorization.",
      objective: "Apply only actions permitted by WATCH.",
      known: "The aggressive fee and factual publication paths are blocked.",
      unknown: "Whether future evidence will refresh or resolve the state.",
      whyItMatters: "Communication and execution are separate bounded capabilities.",
      outputs: [{ id: "rumor-action", kind: "ACTION", title: "Guardrails enforced", summary: "Fee remains at baseline. X Publisher suppresses factual publication.", detail: ["Fee action: NONE", "Publisher: suppressed", "Reason: rumor containment"], dataMode: "REPLAY", capabilityId: "x-publisher", renderKey: "action" }],
      choices: [
        { id: "publish-as-fact", label: "Publish as confirmed", description: "Send the rumor as a factual risk announcement.", outcome: "REJECTED", reasonCode: "NO_OFFICIAL_CONFIRMATION", reveal: [], modal: { ...blockedFeeModal, id: "publication-blocked", title: "Publication blocked", guardrail: "X Publisher cannot convert unresolved evidence into a confirmed statement." } },
        { id: "enforce-watch", label: "Enforce WATCH limits", description: "Keep fee and publication authority closed.", outcome: "ACCEPTED", reveal: ["rumor-action"], nextStageId: "recover" },
      ],
    },
    {
      id: "recover", index: 9, label: "Recover",
      whatHappened: "No supporting evidence refreshed the WATCH record before expiry.",
      objective: "Expire the temporary caution state deterministically.",
      known: "The record has reached its declared expiry.",
      unknown: "None; this mission can return to baseline.",
      whyItMatters: "Temporary protection logic cannot become a permanent discretionary setting.",
      outputs: [{ id: "rumor-recovery", kind: "RECOVERY", title: "Returned to NORMAL", summary: "WATCH expired without promotion. No fee action was ever authorized.", detail: ["Previous: WATCH", "Current: NORMAL", "Action: NONE"], dataMode: "REPLAY", capabilityId: "risk-policy", renderKey: "recovery" }],
      choices: [{ id: "expire-watch", label: "Apply expiry", description: "Return the risk state to baseline.", outcome: "ACCEPTED", reveal: ["rumor-recovery"], completeMission: true, modal: { id: "watch-expired", title: "WATCH expired", previousState: "WATCH", nextState: "NORMAL", cause: "No new qualifying evidence arrived before expiry.", evidence: "The versioned WATCH record reached its declared lifetime.", guardrail: "Expiry is deterministic and cannot be extended silently.", allowed: "Return to baseline policy.", prohibited: "Carry caution or fee changes forward without a new record.", dataMode: "REPLAY", capabilityId: "risk-policy" } }],
    },
  ],
};
