import type { DemoScenario, EvidenceClaimView, RiskRecordView } from "./model";
import { validateRiskRecord } from "./validate";

const ASSET = "0xa8ddb5cd96b5222afe198316e9a57caa642850d5";
const POOL = "0x2a2b11730c2b6d99a58034a869dd810d7300a7b2";

function claim(
  value: Omit<EvidenceClaimView, "company" | "tokenSymbol" | "tokenAddress">,
): EvidenceClaimView {
  return {
    ...value,
    company: "NVIDIA CORPORATION",
    tokenSymbol: "wNVDAx",
    tokenAddress: ASSET,
  };
}

function checked(record: RiskRecordView): RiskRecordView {
  return validateRiskRecord(record);
}

const rumorWatch = checked({
  schemaVersion: "tinjau.risk/1.0.0",
  assessmentId: "fixture:A-rumor-watch",
  assetAddress: ASSET,
  tokenSymbol: "wNVDAx",
  poolIdOrAddress: POOL,
  state: "WATCH",
  reasonCodes: [
    "SINGLE_SOURCE",
    "DUPLICATE_SYNDICATION",
    "NO_OFFICIAL_CONFIRMATION",
    "MARKET_DATA_UNAVAILABLE",
  ],
  humanExplanation:
    "Four reporting outlets collapse to one Wall Street Journal origin, while the simulated social claim adds no promotion authority. The evidence remains WATCH and cannot authorize the aggressive fee path.",
  evidenceCommitment: "0xa69691da55a84968c9076b6f71d6dd64fbca2a647e8a03785dd3598d2f03fc22",
  confidenceBand: "LOW",
  assessedAt: "2026-07-27T20:33:00Z",
  expiresAt: "2026-07-28T20:33:00Z",
  policyVersion: "tinjau.policy/1.0.0",
  dataMode: "REPLAY",
  evidence: [
    claim({
      claimId: "claim-a-001",
      sourceClass: "RUMOR",
      dataMode: "SIMULATED",
      sourceUrl: null,
      sourceId: "simulated://tinjau/T0.2/social/nvda-openai-ohio-2026-07-27",
      publisherOrAuthor: null,
      publishedAt: "2026-07-27T19:11:05Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "Simulated social claim asserting a $250bn NVIDIA backstop.",
      independenceGroup: "simulated:social/nvda-openai-ohio-2026-07-27",
      relation: "ORIGIN",
      officialConfirmation: false,
      expiresAt: "2026-07-28T19:11:05Z",
    }),
    claim({
      claimId: "claim-a-004",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl: null,
      sourceId: "wsj/2026-07-26/nvidia-openai-financing-guarantees",
      publisherOrAuthor: "The Wall Street Journal",
      publishedAt: "2026-07-26T00:00:00Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "Origin report described talks around roughly $250bn in financing guarantees.",
      independenceGroup: "origin:wsj/2026-07-26/nvda-openai-250bn-backstop",
      relation: "ORIGIN",
      officialConfirmation: false,
      expiresAt: "2026-07-29T00:00:00Z",
    }),
    claim({
      claimId: "claim-a-002",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl:
        "https://www.cnbc.com/2026/07/27/nvidia-and-openai-in-talks-for-up-to-250-billion-dollar-ai-backstop.html",
      sourceId: "cnbc.com/2026-07-27/nvidia-openai-250bn-backstop",
      publisherOrAuthor: "CNBC, reporting a Wall Street Journal story",
      publishedAt: "2026-07-27T00:00:00Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "CNBC syndication of the same Wall Street Journal report.",
      independenceGroup: "origin:wsj/2026-07-26/nvda-openai-250bn-backstop",
      relation: "DUPLICATE",
      officialConfirmation: false,
      expiresAt: "2026-07-30T00:00:00Z",
    }),
    claim({
      claimId: "claim-a-003",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl: "https://thenextweb.com/news/nvidia-openai-250-billion-backstop-ohio-data-centre",
      sourceId: "thenextweb.com/2026-07-27/nvidia-openai-250bn-backstop",
      publisherOrAuthor: "The Next Web — Ana Maria Constantin",
      publishedAt: "2026-07-27T20:33:00Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "The Next Web syndication; it states Reuters could not verify the report.",
      independenceGroup: "origin:wsj/2026-07-26/nvda-openai-250bn-backstop",
      relation: "DUPLICATE",
      officialConfirmation: false,
      expiresAt: "2026-07-30T20:33:00Z",
    }),
    claim({
      claimId: "claim-a-005",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl:
        "https://www.datacenterdynamics.com/en/news/nvidia-considers-250bn-backstop-for-openais-planned-10gw-ohio-data-center-report/",
      sourceId: "datacenterdynamics.com/2026-07/nvidia-considers-250bn-backstop",
      publisherOrAuthor: "DataCenterDynamics",
      publishedAt: "2026-07-27T00:00:00Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "DataCenterDynamics syndication of the same origin report.",
      independenceGroup: "origin:wsj/2026-07-26/nvda-openai-250bn-backstop",
      relation: "DUPLICATE",
      officialConfirmation: false,
      expiresAt: "2026-07-30T00:00:00Z",
    }),
  ],
  marketConfirmation: {
    status: "UNAVAILABLE",
    observedAt: "2026-07-27T20:33:00Z",
    blockNumber: "66415344",
    fresh: false,
    antiWickSatisfied: false,
    okxReferencePrice: null,
    xLayerPoolPrice: null,
    basisBps: null,
    drawdownBps: null,
    tradeVelocity: null,
    executableExitDepth: null,
    reasonCodes: ["MARKET_DATA_UNAVAILABLE"],
  },
  action: {
    authorized: false,
    status: "NONE",
    baseFee: "500",
    maxFee: "20000",
    requestedFee: null,
    appliedFee: null,
    maximumDurationSec: 21600,
    txHash: null,
    failureReason: null,
  },
});

const confirmedEventAwaitingMarket = checked({
  schemaVersion: "tinjau.risk/1.0.0",
  assessmentId: "fixture:B-confirmed-protect-market-unavailable",
  assetAddress: ASSET,
  tokenSymbol: "wNVDAx",
  poolIdOrAddress: POOL,
  state: "WATCH",
  reasonCodes: [
    "DUPLICATE_SYNDICATION",
    "MARKET_DATA_UNAVAILABLE",
    "OFFICIAL_FILING",
    "BONDED_EVIDENCE_PASSED",
  ],
  humanExplanation:
    "A qualifying official filing is present, but final OKX/X Layer confirmation is unavailable. The deterministic gate therefore holds at WATCH until fresh market corroboration exists.",
  evidenceCommitment: "0xc4774e470dd970d0778add24d509148ebba6587debc1c93cbf5a4a14b3a5f2da",
  confidenceBand: "MEDIUM",
  assessedAt: "2026-08-17T12:41:33Z",
  expiresAt: "2026-08-18T12:41:33Z",
  policyVersion: "tinjau.policy/1.0.0",
  dataMode: "REPLAY",
  evidence: [
    claim({
      claimId: "claim-b-001",
      sourceClass: "OFFICIAL",
      dataMode: "REPLAY",
      sourceUrl: "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000069/nvda-20260817.htm",
      sourceId: "edgar:0001045810-26-000069/nvda-20260817.htm",
      publisherOrAuthor: "NVIDIA CORPORATION — SEC EDGAR filer",
      publishedAt: "2026-08-17T12:41:33Z",
      eventType: "MATERIAL_DEFINITIVE_AGREEMENT_AND_DIRECT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "SEC 8-K discloses residual value guaranties capped at $105bn.",
      independenceGroup: "official:edgar/0001045810-26-000069",
      relation: "ORIGIN",
      officialConfirmation: true,
      expiresAt: "2026-08-20T12:41:33Z",
    }),
    claim({
      claimId: "claim-b-002",
      sourceClass: "OFFICIAL",
      dataMode: "REPLAY",
      sourceUrl:
        "https://www.sec.gov/Archives/edgar/data/1045810/000104581026000069/sbeoainvidia-portsrelease.htm",
      sourceId: "edgar:0001045810-26-000069/sbeoainvidia-portsrelease.htm",
      publisherOrAuthor: "NVIDIA CORPORATION — Exhibit 99.1",
      publishedAt: "2026-08-17T12:41:33Z",
      eventType: "MATERIAL_DEFINITIVE_AGREEMENT_AND_DIRECT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "Exhibit 99.1 supports the official filing but is the same accession.",
      independenceGroup: "official:edgar/0001045810-26-000069",
      relation: "SUPPORTS",
      officialConfirmation: true,
      expiresAt: "2026-08-20T12:41:33Z",
    }),
    claim({
      claimId: "claim-b-003",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl: null,
      sourceId: "wsj/2026-08-14/nvidia-scales-back-ohio-guarantee",
      publisherOrAuthor: "The Wall Street Journal",
      publishedAt: "2026-08-14T00:00:00Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "Revised origin reported an initial guarantee below $120bn.",
      independenceGroup: "origin:wsj/2026-08-14/nvda-ohio-guarantee-revision",
      relation: "SUPPORTS",
      officialConfirmation: true,
      expiresAt: "2026-08-17T00:00:00Z",
    }),
    claim({
      claimId: "claim-b-004",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl: "https://finance.yahoo.com/technology/ai/articles/nvidia-scales-back-250-billion-234356524.html",
      sourceId: "reuters-via-yahoo/2026-08-14T23:43:56Z/nvidia-scales-back-guarantee",
      publisherOrAuthor: "Reuters — syndicated by Yahoo Finance",
      publishedAt: "2026-08-14T23:43:56Z",
      eventType: "CONTINGENT_FINANCIAL_OBLIGATION",
      claimTextOrPointer: "Reuters syndication of the revised Wall Street Journal origin.",
      independenceGroup: "origin:wsj/2026-08-14/nvda-ohio-guarantee-revision",
      relation: "DUPLICATE",
      officialConfirmation: true,
      expiresAt: "2026-08-17T23:43:56Z",
    }),
    claim({
      claimId: "claim-b-005",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl:
        "https://www.theinformation.com/articles/nvidia-talks-invest-3-billion-sb-energy-part-openai-data-center-deal",
      sourceId: "theinformation.com/2026-08-15/nvidia-talks-invest-3-billion-sb-energy",
      publisherOrAuthor: "The Information",
      publishedAt: "2026-08-15T00:00:00Z",
      eventType: "STRATEGIC_PARTNERSHIP_OR_INVESTMENT",
      claimTextOrPointer: "Independent report supported the direction but overstated the equity magnitude.",
      independenceGroup: "origin:theinformation/2026-08-15/nvda-sbenergy-3b",
      relation: "SUPPORTS",
      officialConfirmation: true,
      expiresAt: "2026-08-18T00:00:00Z",
    }),
    claim({
      claimId: "claim-b-006",
      sourceClass: "NEWS",
      dataMode: "REPLAY",
      sourceUrl: "https://finance.yahoo.com/technology/ai/articles/nvidia-talks-invest-3-billion-193826586.html",
      sourceId: "reuters-via-yahoo/2026-08-15T19:38:26Z/nvidia-talks-invest-3-billion",
      publisherOrAuthor: "Reuters — syndicated by Yahoo Finance",
      publishedAt: "2026-08-15T19:38:26Z",
      eventType: "STRATEGIC_PARTNERSHIP_OR_INVESTMENT",
      claimTextOrPointer: "Reuters syndication of The Information origin.",
      independenceGroup: "origin:theinformation/2026-08-15/nvda-sbenergy-3b",
      relation: "DUPLICATE",
      officialConfirmation: true,
      expiresAt: "2026-08-18T19:38:26Z",
    }),
  ],
  marketConfirmation: {
    status: "UNAVAILABLE",
    observedAt: "2026-08-17T12:41:33Z",
    blockNumber: "68201457",
    fresh: false,
    antiWickSatisfied: false,
    okxReferencePrice: null,
    xLayerPoolPrice: null,
    basisBps: null,
    drawdownBps: null,
    tradeVelocity: null,
    executableExitDepth: null,
    reasonCodes: ["MARKET_DATA_UNAVAILABLE"],
  },
  action: {
    authorized: false,
    status: "NONE",
    baseFee: "500",
    maxFee: "20000",
    requestedFee: null,
    appliedFee: null,
    maximumDurationSec: 21600,
    txHash: null,
    failureReason: null,
  },
});

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    slug: "rumor-watch",
    shortLabel: "Scene A",
    title: "Rumor enters; authorization does not",
    role: "False-rumor and degraded-market control",
    sourceFile: "apps/server/scenarios/scenario-a-rumor-watch.json",
    sourceChecksum: "a69691da55a84968c9076b6f71d6dd64fbca2a647e8a03785dd3598d2f03fc22",
    record: rumorWatch,
    limitations: [
      "Frozen replay plus one explicitly simulated social claim.",
      "The replay window contains zero observed swaps, so this scene has no economic row.",
      "No final market-confirmation payload or action transaction has been handed off.",
    ],
  },
  {
    slug: "confirmed-event",
    shortLabel: "Scene B",
    title: "Official evidence arrives; market gate remains required",
    role: "Conditional protection path shown before confirmation integration",
    sourceFile: "apps/server/scenarios/scenario-b-confirmed-protect.json",
    sourceChecksum: "c4774e470dd970d0778add24d509148ebba6587debc1c93cbf5a4a14b3a5f2da",
    record: confirmedEventAwaitingMarket,
    limitations: [
      "Official SEC evidence is frozen and source-pinned.",
      "PROTECT is pre-registered only if market confirmation is CONFIRMED and fresh.",
      "Until the final confirmation and transaction records exist, this fixture must render WATCH and no action.",
    ],
  },
];

export function getDemoScenario(slug?: string): DemoScenario {
  return DEMO_SCENARIOS.find((scenario) => scenario.slug === slug) ?? DEMO_SCENARIOS[0];
}
